name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '* * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repos' README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vharivinay/blog-post-workflow@forRST
        with:
          feed_list: 'https://naturalfreakquency.wordpress.com'
          readme_path: ./README.rst
